<?php

namespace Proxies\__CG__\NB\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PointEmbarquement extends \NB\MainBundle\Entity\PointEmbarquement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'id', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'nom', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'compagnie', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'createdAt', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'updatedAt', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'isActive', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'longitude', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'lattitude');
        }

        return array('__isInitialized__', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'id', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'nom', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'compagnie', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'createdAt', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'updatedAt', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'isActive', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'longitude', '' . "\0" . 'NB\\MainBundle\\Entity\\PointEmbarquement' . "\0" . 'lattitude');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PointEmbarquement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function isIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsActive', array());

        return parent::isIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($isActive));

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompagnie($compagnie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompagnie', array($compagnie));

        return parent::setCompagnie($compagnie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompagnie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompagnie', array());

        return parent::getCompagnie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', array($longitude));

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', array());

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLattitude($lattitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLattitude', array($lattitude));

        return parent::setLattitude($lattitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLattitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLattitude', array());

        return parent::getLattitude();
    }

}
