<?php

namespace Proxies\__CG__\NB\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Axes extends \NB\MainBundle\Entity\Axes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'id', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'nom', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'source', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'destination', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'distance', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'description', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'photo', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'createdAt', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'updatedAt', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'isActive', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'capacite', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'type', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'type_bus');
        }

        return array('__isInitialized__', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'id', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'nom', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'source', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'destination', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'distance', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'description', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'photo', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'createdAt', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'updatedAt', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'isActive', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'capacite', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'type', '' . "\0" . 'NB\\MainBundle\\Entity\\Axes' . "\0" . 'type_bus');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Axes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function getDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistance', array());

        return parent::getDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistance($distance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistance', array($distance));

        return parent::setDistance($distance);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacite', array());

        return parent::getCapacite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacite($capacite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacite', array($capacite));

        return parent::setCapacite($capacite);
    }

    /**
     * {@inheritDoc}
     */
    public function isType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isType', array());

        return parent::isType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function isTypeBus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTypeBus', array());

        return parent::isTypeBus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeBus($type_bus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeBus', array($type_bus));

        return parent::setTypeBus($type_bus);
    }

    /**
     * {@inheritDoc}
     */
    public function setSource($source)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', array($source));

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', array());

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestination($destination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestination', array($destination));

        return parent::setDestination($destination);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestination()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestination', array());

        return parent::getDestination();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', array($photo));

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', array());

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($isActive));

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', array());

        return parent::getIsActive();
    }

}
