nb_main:
    resource: "@NBMainBundle/Resources/config/routing.yml"
    prefix:   /
nb_app:
    resource: "@NBMainBundle/Resources/config/app.yml"
    prefix:   /app


nb_user:
    resource: "@NBUsersBundle/Resources/config/routing.yml"
    prefix:   /



login:
    pattern:   /login
    defaults:  { _controller: NBUsersBundle:Security:login }
change_password:
    pattern:   /changer-mot-de-passe
    defaults:  { _controller: NBUsersBundle:Security:changePassword }



logout:
    pattern:   /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /registration
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile