<?php

namespace NB\MainBundle\Repository;

/**
 * AxesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AxesRepository extends \Doctrine\ORM\EntityRepository
{
}
