<?php

namespace NB\MainBundle\Repository;

/**
 * PointEmbarquementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointEmbarquementRepository extends \Doctrine\ORM\EntityRepository
{
}
