<?php

namespace NB\MainBundle\Repository;

/**
 * QuartierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuartierRepository extends \Doctrine\ORM\EntityRepository
{
}
