<?php

namespace NB\MainBundle\Repository;

/**
 * SeatsellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeatsellerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotal(){

        $qb = $this->createQueryBuilder('s');
        $qb->setMaxResults( 1 );
        $qb->orderBy('s.id', 'DESC');
        return $qb->getQuery()->getSingleResult();
    }

    public function getByUserId($user_id){

        $queryBuilder = $this
            ->createQueryBuilder('s')
            ->innerJoin('s.users', 'u')
            ->addSelect('u')
            //    ->leftJoin('t.frequency', 'frequency')
            ->where('u.id = :user_id')
            //->andWhere('(:gd) in f')
            //->andWhere('(:gd) in f')
            ->setParameters(array('user_id' => $user_id ))
        ;
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
      //  dump($results); exit;

        return $results[0];

    }
}
