<?php

namespace NB\MainBundle\Repository;

/**
 * VoyagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTravelByRoute($from, $to, $doj)
    {
        $queryBuilder = $this
            ->createQueryBuilder('v')
            ->innerJoin('v.axes', 'ax')
            ->leftJoin('v.compagnie', 'c')
            ->addSelect('c')
            ->where('ax.source = :fc')
            ->andWhere('ax.destination = :tc')
            ->andWhere('v.isActive = :active')
            //->andWhere('(:gd) in f')
            //->andWhere('(:gd) in f')
            ->setParameters(array('fc' => $from, 'tc' => $to, 'active' => true ))
        ;
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        // On retourne ces résultats

       // dump($results); exit;

        return $results;
    }
}
