<?php

namespace Proxies\__CG__\NB\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaction extends \NB\MainBundle\Entity\Transaction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'token', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'uid', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'confimationCode', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'providerName', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'status', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'reservation', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'createdAt');
        }

        return array('__isInitialized__', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'token', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'uid', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'confimationCode', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'providerName', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'status', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'reservation', '' . "\0" . 'NB\\MainBundle\\Entity\\Transaction' . "\0" . 'createdAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transaction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setUid($uid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUid', array($uid));

        return parent::setUid($uid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUid', array());

        return parent::getUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfimationCode($confimationCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfimationCode', array($confimationCode));

        return parent::setConfimationCode($confimationCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfimationCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfimationCode', array());

        return parent::getConfimationCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setProviderName($providerName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProviderName', array($providerName));

        return parent::setProviderName($providerName);
    }

    /**
     * {@inheritDoc}
     */
    public function getProviderName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProviderName', array());

        return parent::getProviderName();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservation($reservation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservation', array($reservation));

        return parent::setReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservation', array());

        return parent::getReservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

}
