<?php

namespace Proxies\__CG__\NB\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Seatseller extends \NB\MainBundle\Entity\Seatseller implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'id', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'nom', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'prenom', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'nomAgence', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'ville', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'commune', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'quartier', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'contact', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'numero_nina', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'code', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'email', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'createdAt', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'updatedAt', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'isActive', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'users');
        }

        return array('__isInitialized__', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'id', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'nom', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'prenom', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'nomAgence', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'ville', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'commune', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'quartier', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'contact', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'numero_nina', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'code', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'email', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'createdAt', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'updatedAt', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'isActive', '' . "\0" . 'NB\\MainBundle\\Entity\\Seatseller' . "\0" . 'users');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Seatseller $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUsers(\NB\UsersBundle\Entity\Users $users = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsers', array($users));

        return parent::setUsers($users);
    }

    /**
     * {@inheritDoc}
     */
    public function addUsers(\NB\UsersBundle\Entity\Users $users)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsers', array($users));

        return parent::addUsers($users);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsers(\NB\UsersBundle\Entity\Users $users)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsers', array($users));

        return parent::removeUsers($users);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', array());

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroNina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroNina', array());

        return parent::getNumeroNina();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroNina($numero_nina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroNina', array($numero_nina));

        return parent::setNumeroNina($numero_nina);
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomAgence($nomAgence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomAgence', array($nomAgence));

        return parent::setNomAgence($nomAgence);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomAgence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomAgence', array());

        return parent::getNomAgence();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommune($commune)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommune', array($commune));

        return parent::setCommune($commune);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommune', array());

        return parent::getCommune();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuartier($quartier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuartier', array($quartier));

        return parent::setQuartier($quartier);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuartier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuartier', array());

        return parent::getQuartier();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($isActive));

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', array());

        return parent::getIsActive();
    }

}
